/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.RegistroCliente;
import controlador.RegistroProducto;
import controlador.RegistroVenta;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Producto;
import modelo.Venta;

/**
 *
 * @author Nicooking23
 */
public class Listados extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Listados.class.getName());

    RegistroProducto rgp = new RegistroProducto();
    RegistroCliente rgc = new RegistroCliente();
    RegistroVenta rgv = new RegistroVenta();
    
    /**
     * Creates new form Listados
     */
    public Listados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        bntBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar/Eliminar Registro Ventas");

        jPanel1.setBackground(new java.awt.Color(169, 113, 85));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 248, 241));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reportes/Listados");

        jLabel2.setForeground(new java.awt.Color(250, 248, 241));
        jLabel2.setText("Busqueda por filtro");

        txtBusqueda.setToolTipText("Ingrese busqueda");

        bntBuscar.setBackground(new java.awt.Color(250, 248, 241));
        bntBuscar.setForeground(new java.awt.Color(62, 39, 35));
        bntBuscar.setText("Buscar");
        bntBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bntBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntBuscar))
                .addGap(0, 42, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(245, 236, 206));

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Venta", "Fecha/Hora", "Producto", "Cliente", "Cantidad Total", "Total pagado", "Método Pago"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDatos);

        btnModificar.setBackground(new java.awt.Color(121, 85, 72));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(250, 248, 241));
        btnModificar.setText("Modificar");

        btnEliminar.setBackground(new java.awt.Color(121, 85, 72));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(250, 248, 241));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModificar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarActionPerformed
        // TODO add your handling code here:
        int id_venta,id_producto,id_cliente,cantidad,total;
        Date fecha_venta;
        String fechaStr,metodo_pago,nomProducto = "",nomCliente = "";
        
        SimpleDateFormat fechaFormat = new SimpleDateFormat("dd/MM/yyyy");
        
        DefaultTableModel modelo = (DefaultTableModel) this.tblDatos.getModel();
        modelo.setRowCount(0);
        // Verificar si es Buscar Todos o Buscar con un ID
        try {
            id_venta = Integer.parseInt(this.txtBusqueda.getText());
        } catch (Exception e) {
            id_venta = 0;
        }
        //pongo la tabla vacía
        modelo.setRowCount(0);
        if(id_venta == 0){ //Buscar Todos
            ArrayList<Venta> lista = rgv.buscarTodos();
            for (Venta aux : lista) {
                id_venta = aux.getId_venta();
                id_producto = aux.getId_producto();
                id_cliente = aux.getId_cliente();
                cantidad = aux.getCantidad();
                total = aux.getTotal();
                fechaStr = fechaFormat.format(aux.getFecha_venta());
                metodo_pago = aux.getMetodo_pago();
                //logica para buscar por nombre
                Producto producto = rgp.buscarUnProducto(id_producto);
                if(producto != null){
                    nomProducto = producto.getNombre();
                }else{
                    nomProducto = "Producto No encontrado (ID " + id_producto + ")";
                }
                Cliente cliente = rgc.buscarUnCliente(id_cliente);
                if(cliente != null){
                    nomCliente = cliente.getNombre();
                }else{
                    nomCliente = "Cliente No encontrado (ID " + id_cliente + ")";
                }
                modelo.addRow(new Object[]{id_venta,fechaStr,nomProducto,nomCliente,cantidad,total,metodo_pago}); 
            }
        }else{  //consultar por UN nombre el producto(por su ID)
            Venta venta = rgv.buscarUnaVenta(id_venta);
            if(venta != null){
            id_producto = venta.getId_producto();
            id_cliente = venta.getId_cliente();
            cantidad = venta.getCantidad();
            total = venta.getTotal();
            fechaStr = fechaFormat.format(venta.getFecha_venta());
            metodo_pago = venta.getMetodo_pago();
            
            Producto producto = rgp.buscarUnProducto(id_producto);
            // Buscar Nombre del Producto
            nomProducto = (producto != null) ? producto.getNombre() : "Producto No encontrado (ID " + id_producto + ")";
            // Buscar Nombre del Cliente
            Cliente cliente = rgc.buscarUnCliente(id_cliente);
            nomCliente = (cliente != null) ? cliente.getNombre() : "Cliente No encontrado (ID " + id_cliente + ")";
            modelo.addRow(new Object[]{id_venta,fechaStr,nomProducto,nomCliente,cantidad,total,metodo_pago}); 
            }

        }        
    }//GEN-LAST:event_bntBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = this.tblDatos.getSelectedRow();
        if(fila < 0){  //NO ha seleccionado fila en la tabla
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una fila", "Validación", JOptionPane.INFORMATION_MESSAGE);
            this.tblDatos.requestFocus();
            return;
        }else{
            //obtengo el id del libro seleccionado en la tabla
            int id_producto = (int) this.tblDatos.getValueAt(fila, 0);
            if(rgp.eliminarProducto(id_producto)){
                JOptionPane.showMessageDialog(this, "Se eliminó correctamente el Producto con el ID: " + id_producto, "Información", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "NO se eliminó el Producto con el ID: " + id_producto, "Error", JOptionPane.ERROR_MESSAGE);
            }
            this.txtBusqueda.setText("");
            this.bntBuscar.doClick(); //simular el click en el botón
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
/**/
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
