/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;


import controlador.RegistroProducto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Producto;

/**
 *
 * @author Nicooking23
 */
public class Productos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Productos.class.getName());

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgCategoria = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtIngredientes = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        chkEstado = new javax.swing.JCheckBox();
        btnLimpiar = new javax.swing.JButton();
        btnGuardarPr = new javax.swing.JButton();
        optA = new javax.swing.JRadioButton();
        optB = new javax.swing.JRadioButton();
        optC = new javax.swing.JRadioButton();
        optD = new javax.swing.JRadioButton();
        optE = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Producto");

        jPanel1.setBackground(new java.awt.Color(245, 236, 206));

        jLabel2.setForeground(new java.awt.Color(62, 39, 35));
        jLabel2.setText("Nombre");

        txtNombre.setToolTipText("Ingrese el nombre del producto");

        jLabel3.setForeground(new java.awt.Color(62, 39, 35));
        jLabel3.setText("Categoría");

        jLabel4.setForeground(new java.awt.Color(62, 39, 35));
        jLabel4.setText("Descripción");

        jLabel5.setForeground(new java.awt.Color(62, 39, 35));
        jLabel5.setText("Ingredientes");

        jLabel6.setForeground(new java.awt.Color(62, 39, 35));
        jLabel6.setText("Precio");

        jLabel7.setForeground(new java.awt.Color(62, 39, 35));
        jLabel7.setText("Stock disponible");

        txtDescripcion.setToolTipText("Ingrese una descripción");

        txtIngredientes.setToolTipText("Ingrese los ingredientes");

        txtPrecio.setToolTipText("Ingrese el precio");

        txtStock.setToolTipText("Ingrese Stock Disponible");

        chkEstado.setForeground(new java.awt.Color(62, 39, 35));
        chkEstado.setText("Disponible?");
        chkEstado.setToolTipText("");

        btnLimpiar.setBackground(new java.awt.Color(121, 85, 72));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(250, 248, 241));
        btnLimpiar.setText("Limpiar");

        btnGuardarPr.setBackground(new java.awt.Color(121, 85, 72));
        btnGuardarPr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardarPr.setForeground(new java.awt.Color(250, 248, 241));
        btnGuardarPr.setText("Guardar");
        btnGuardarPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPrActionPerformed(evt);
            }
        });

        btgCategoria.add(optA);
        optA.setForeground(new java.awt.Color(62, 39, 35));
        optA.setText("Bebida caliente");

        btgCategoria.add(optB);
        optB.setForeground(new java.awt.Color(62, 39, 35));
        optB.setText("Bebida fría");
        optB.setToolTipText("");

        btgCategoria.add(optC);
        optC.setForeground(new java.awt.Color(62, 39, 35));
        optC.setText("Pastelería");

        btgCategoria.add(optD);
        optD.setForeground(new java.awt.Color(62, 39, 35));
        optD.setText("Sandwish");

        btgCategoria.add(optE);
        optE.setForeground(new java.awt.Color(62, 39, 35));
        optE.setText("Complemento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGuardarPr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(optB)
                            .addComponent(optC)
                            .addComponent(optA)
                            .addComponent(optD))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(optE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(chkEstado)))
                        .addContainerGap(14, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(optA, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optD)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(optE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkEstado))
                    .addComponent(jLabel6))
                .addGap(45, 45, 45)
                .addComponent(btnLimpiar)
                .addGap(18, 18, 18)
                .addComponent(btnGuardarPr)
                .addGap(47, 47, 47))
        );

        jPanel3.setBackground(new java.awt.Color(169, 113, 85));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(250, 248, 241));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Gestión de Productos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPrActionPerformed
        // TODO add your handling code here:
        // codigoProducto,precio,stock,nombrePr,categoria,descripcion,ingredientes,estado
        String nombre,descripcion,ingredientes;
        String categoria = null;
        int precio, stock;
        boolean estado;
        
        nombre = this.txtNombre.getText();
        if(nombre.isBlank()){
            JOptionPane.showMessageDialog(this, "Ingrese nombre", "Validación", JOptionPane.WARNING_MESSAGE);
            this.txtNombre.requestFocus();
            return;
        }
        
        // --- LÓGICA PARA OBTENER LA CATEGORÍA SELECCIONADA ---
        if(this.optA.isSelected()){
            categoria = "Bebida Caliente"; //bebida caliente
        }else if(this.optB.isSelected()){
            categoria = "Bebida fría"; //bebida fria
        }else if(this.optC.isSelected()){
            categoria = "Pastelería"; //pasteleria
        }else if(this.optD.isSelected()){
            categoria = "Sandwish"; //sandwish
        }else if(this.optE.isSelected()){
            categoria = "Complemento"; //complemento
        }
        
        if(this.btgCategoria.getSelection() == null){
            JOptionPane.showMessageDialog(this, "Seleccione una categoría", "Validación", JOptionPane.WARNING_MESSAGE);
            return; // Detiene la ejecución si no hay selección
        }
        descripcion = this.txtDescripcion.getText();
        if(descripcion.isBlank()){
            JOptionPane.showMessageDialog(this, "Ingrese descripción", "Validación", JOptionPane.WARNING_MESSAGE);
            this.txtDescripcion.requestFocus();
            return;
        }
        
        ingredientes = this.txtIngredientes.getText();
        if(ingredientes.isBlank()){
            JOptionPane.showMessageDialog(this, "Ingrese ingredientes", "Validación", JOptionPane.WARNING_MESSAGE);
            this.txtIngredientes.requestFocus();
            return;
        }
        
        try {
            precio = Integer.parseInt(this.txtPrecio.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ingrese precio", "Validación", JOptionPane.WARNING_MESSAGE);
            this.txtPrecio.requestFocus();
            return;
        }
        
        try {
            stock = Integer.parseInt(this.txtStock.getText());
            if(stock < 0){
                JOptionPane.showMessageDialog(this, "El stock no puede ser negativo", "Validación", JOptionPane.WARNING_MESSAGE);
                this.txtStock.requestFocus();
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ingrese Stock", "Validación", JOptionPane.WARNING_MESSAGE);
            this.txtStock.requestFocus();
            return;
        }
        
        estado = this.chkEstado.isSelected();
        
        //Creo un objeto producto y le doy valor a sus atributos
        Producto producto = new Producto(0, precio, stock, nombre, descripcion, ingredientes, categoria, estado);
        RegistroProducto rg = new RegistroProducto();
        //Validar si Producto ya existe
        if(rg.buscarUnProductoNombre(nombre).getNombre() == null){
            if(rg.agregarProducto(producto)){
                JOptionPane.showMessageDialog(this, "Producto agregado exitosamente!!", "Información", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Producto NO fué agregado", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Producto" + nombre + "YA EXISTE","Validación", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnGuardarPrActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgCategoria;
    private javax.swing.JButton btnGuardarPr;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JCheckBox chkEstado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton optA;
    private javax.swing.JRadioButton optB;
    private javax.swing.JRadioButton optC;
    private javax.swing.JRadioButton optD;
    private javax.swing.JRadioButton optE;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIngredientes;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
